import json
from typing import Any

import httpx

import constants


class Config(dict[str, Any]):
    def __init__(self):
        super().__init__()
        for name, value in vars(constants).items():
            if name.startswith('__'):
                continue
            self[name] = value

    async def download_json(self):
        async with httpx.AsyncClient() as client:
            response = await client.get(
                'https://raw.githubusercontent.com/jesseklm/coj-maps-downloader/refs/heads/master/config.json')
        response.raise_for_status()
        data = json.loads(response.text)
        data.pop('__meta__', None)
        self.update(data)

    def write_json(self):
        payload: dict[str, Any] = {'__meta__': {'autogenerated': True, }}
        payload.update(self)
        with open('config.json', 'w', encoding='utf-8') as f:
            json.dump(payload, f, indent=1)


CONFIG = Config()

if __name__ == '__main__':
    CONFIG.write_json()
